### ISSUE TITLE
[Bug] Not all tasks visible all the time

### ISSUE THREAD

**Issue by Sluimerstand** [ThingEngineering/choretracker#10]
When I first loaded in the addon, the alchemy header wasn't visible at all.
I reloaded, now the header is visible, but not the tasks underneath:
![image](https://github.com/user-attachments/assets/13c76068-3e55-4181-9f40-e6df8dba98b8)

Only after reloading _again_ it shows the tasks properly.

**Comment by Sluimerstand** [comment]
I guess you could cache the info? Save the highest recorded info returned by `C_TradeSkillUI.GetProfessionInfoBySkillLineID(skillLineID)` 🤔

**Comment by madcowfred** [comment]
This should be better in v11.0.2.6:
- can get the latest skill level once again
- puts an annoying pink message when it needs you to open a profession (mostly enabling Dragonflight profession chores)
- doesn't overwrite the known skill level for a pre-current profession
