### ISSUE TITLE
Missing/Changed Tasks in TWW

### ISSUE THREAD

**Issue by F-Lambda** [ThingEngineering/choretracker#11]
There's a few changes in available weekly quests.

New ones that are missing are a Ringing Deeps weekly, "[Rollin Down in the Deeps](https://www.wowhead.com/quest=82946)" (quest=82946), the [Sparks of War](https://www.wowhead.com/item=219934) quests (equivalent to DF Sparks of Life), listed [here](https://www.wowhead.com/beta/item=219934/spark-of-war#objective-of), and the "Special Assignment" weeklies unlocked after doing 3 WQs in a zone, such as "Special Assignment: Rise of the Colossals" (there seems to be two quests for these, one for [unlocking](https://www.wowhead.com/quest=82157) and one for [completing](https://www.wowhead.com/quest=82787)). There's also "[The Key to Success](https://www.wowhead.com/quest=84370)" (quest=84370) obtained after finding an [Archaic Cipher Key](https://www.wowhead.com/item=227794), though this last one doesn't seem to be active yet (Season 1 start, maybe).

There's also some existing quests that have been deactivated: Pandaria Remix event, Radiant Echoes event, DF Last Hurrah, DF Aiding the Accord, and DF Sparks of Life.

Edit: It'd also be good to add a timer for Beledar's Shadow, as that's the only time the rare elite [Beledar's Spawn](https://www.wowhead.com/npc=207802/beledars-spawn) can... spawn. It goes dark for 30 minutes every 3 hours, with the first time being 1 hour after daily reset (according to [this Wowhead comment](https://www.wowhead.com/npc=207802/beledars-spawn#comments:id=5879919)).

Edit2: This code seems to work for Beledar's Shadow, the Ringing Deeps weekly, and the Warmode quests:
```
                {
                    key = 'rollinDownInTheDeeps',
                    minimumLevel = 80,
                    entries = {
                        { quest = 82946 }, -- Rollin' Down in the Deeps
                    }
                },
                {
                    key = 'sparksOfWar',
                    entries = {
                        { quest = 81793 }, -- Sparks of War: Isle of Dorn
                        { quest = 81794 }, -- Sparks of War: The Ringing Deeps
                        { quest = 81795 }, -- Sparks of War: Hallowfall
                        { quest = 81796 }, -- Sparks of War: Azj-Kahet
                    },
                },
```

```
        {
            key = 'beledarsShadow',
            minimumLevel = 70,
            interval = 3 * 60 * 60,
            duration = 30 * 60,
            offset = 60 * 60,
        },
```

**Comment by madcowfred** [comment]
Thanks, mostly added in v11.0.2.6 (not Special Assignments or the key thing)

**Comment by Sluimerstand** [comment]
84084 is (so far the only) weekly gathering quest for Enchanting (it's treated like herb/mine/skin atm)
82678 is currently the "Worldsoul weekly" (instead of choosing 1 of 4)

**Comment by F-Lambda** [comment]
> 82678 is currently the "Worldsoul weekly" (instead of choosing 1 of 4)

Yeah, seems like the Archives quests might be alternating with the Worldsoul quests? not sure how the addon can show that automatically, especially since it seems like the Archives quests might have some kind of progression

**Comment by F-Lambda** [comment]
The following seems to add the queued PvP quests properly:

```
                {
                    key = 'pvpHonor',
                    minimumLevel = 80,
                    pick = 2,
                    alwaysShowObjectives = true,
                    entries = {
                        { quest = 80184 }, -- Preserving in Battle
                        { quest = 80185 }, -- Preserving Solo
                        { quest = 80186 }, -- Preserving in War
                        { quest = 80187 }, -- Preserving in Skirmishes
                        { quest = 80188 }, -- Preserving in Arenas
                        { quest = 80189 }, -- Preserving in Teamwork
                    },
                },
```

English localization addition:
```
L['chore:warWithin:patch_11_0_0:quests:pvpHonor'] = 'Honor'
```

**Comment by madcowfred** [comment]
Added the Preserving quests in v11.0.2.19.
