### ISSUE TITLE
[Feature Request] Expansion disable option

### ISSUE THREAD

**Issue by EKE00372** [ThingEngineering/choretracker#15]
Too many Dragonflight chores; disable them one by one is really tedious.

**Comment by madcowfred** [comment]
Fixed with [v11.0.2.7](https://github.com/ThingEngineering/choretracker/releases/tag/v11.0.2.7)

- Dragonflight chores default to off
- Added "Disable ALL DF chores" and "Enable ALL DF chores" buttons to options
