### ISSUE TITLE
[Feature Request] Section Order

### ISSUE THREAD

**Issue by F-Lambda** [ThingEngineering/choretracker#17]
Currently, the section order is Dragonflight, War Within, and then professions. It'd be nice if you could set the order of the top sections, so that you could have it be War Within, Dragonflight, Professions, or Professions, War Within, Dragonflight, for example.

This would allow to have Dragonflight weeklies tracked, for filling in transmog/pets, while keeping current expansion stuff prioritized.

**Comment by madcowfred** [comment]
Added options for this in v11.0.2.19.
