### ISSUE TITLE
[Feature Request] Upload addon to Wago

### ISSUE THREAD

**Issue by lyledouglass** [ThingEngineering/choretracker#19]
I've primarily swapped over to wago for ease of use (being able to update addons/WAs in on place, etc). It would be great to be able to get this from there. 

With this being hosted in Github, you could utilize the [BigWigs Packager](https://github.com/BigWigsMods/packager) in place the of the current action step to upload to Curse, Wago, and create a Github release all in one.

**Comment by madcowfred** [comment]
There's been [a project](https://addons.wago.io/addons/choretracker) over there for a while, I just apparently broke the automatic release thing it can do. Should be working again, I'll try to find time to update the description/images/etc.
