### ISSUE TITLE
Add general display option for not showing (sub)objectives

### ISSUE THREAD

**Issue by Sluimerstand** [ThingEngineering/choretracker#2]
Before:
![image](https://github.com/ThingEngineering/choretracker/assets/29845810/293eefb8-1166-4026-b1ba-0f8fda2ca6df)

After:
![image](https://github.com/ThingEngineering/choretracker/assets/29845810/078d1d9a-aa98-4c4a-9508-3092fb67c457)
(But with the removed lines not being lines. Love you Freddie!)

**Comment by madcowfred** [comment]
Added in v10.2.0.10
