### ISSUE TITLE
[Feature Request] New Pinnacle Weekly Story Quest

### ISSUE THREAD

**Issue by Sefank** [ThingEngineering/choretracker#20]
In short,  there's a new pinnacle quest this week in TWW, replacing the choice of four "worldsoul" activities offered the first week - [Archives: The First Disc](https://www.wowhead.com/quest=82678/archives-the-first-disc). See more in [News Post in wowhead](https://www.wowhead.com/news/new-pinnacle-weekly-story-quest-defeat-rares-loot-treasures-and-complete-346387).

This may be tracked along with the "worldsoul" item in the addon.

**Comment by madcowfred** [comment]
Added in v11.0.2.9
