### ISSUE TITLE
Lower frame minimum sizing/height

### ISSUE THREAD

**Issue by ThisIsFineCopium** [ThingEngineering/choretracker#26]
I only need / want to track a couple things but the minimum height only allows for this size.

![image](https://github.com/user-attachments/assets/1a03f63a-b001-46c3-861c-c7d0ded5dc62)

Can you decrease the minimum height, so i can collapse it a bit further to hide the blank space.

**Comment by madcowfred** [comment]
Changed in v11.0.2.15

**Comment by ThisIsFineCopium** [comment]
Thank you, that's perfect.
