### ISSUE TITLE
[Bug] Sparks of War quest getting dropped and re-accepted on logout

### ISSUE THREAD

**Issue by F-Lambda** [ThingEngineering/choretracker#36]
Per title, the "auto accept quests" setting is causing the Sparks of War quest to get dropped and reaccepted each logout, resetting progress.

**Comment by madcowfred** [comment]
The quest was being dropped any time you logged out. Nothing to do with ChoreTracker, it just made it very noticeable that Blizzard broke their shit :|

**Comment by F-Lambda** [comment]
Oh that's definitely unfortunate. Will be sure to submit an in-game bug report then.
