### ISSUE TITLE
[Feature/Bug] "Celebrate Good Fun!" not a true daily

### ISSUE THREAD

**Issue by F-Lambda** [ThingEngineering/choretracker#37]
Per title, this anniversary quest isn't a true daily. It's hard to tell at this point, but [comments on the wowhead page](https://www.wowhead.com/quest=84616/celebrate-good-fun#comments) think that it might be some kind of "Daily but only after the buff runs out" (it can't be clicked off) (or the quest is just bugged, lol).

**Comment by madcowfred** [comment]
Fixed in v11.0.5.4
