### ISSUE TITLE
Feature request: click passthrough

### ISSUE THREAD

**Issue by Sluimerstand** [ThingEngineering/choretracker#6]
I have it in the corner over top of my raid frames, but even when invisible because empty my mouse is ofc taken by the Chore Tracker frame. >:

**Comment by Sluimerstand** [comment]
Strata level also circumvents this.

**Comment by Sluimerstand** [comment]
Turns out it doesn't; even on Background it blocks the mouse, I'm just dumb. xD

**Comment by madcowfred** [comment]
Added in v11.0.2.10
