### ISSUE TITLE
Lua error on startup: Attempt to index field 'skillLines' (a nil value)

### ISSUE THREAD

**Issue by Amethice** [ThingEngineering/choretracker#9]
Getting this error whenever I start the game:

5x ChoreTracker/Modules/Display.lua:208: attempt to index field 'skillLines' (a nil value)
[string "@ChoreTracker/Modules/Display.lua"]:208: in function `ConfigChanged'
[string "@ChoreTracker/Modules/Display.lua"]:310: in function `Redraw'
[string "@ChoreTracker/Modules/Display.lua"]:77: in function <ChoreTracker/Modules/Display.lua:41>
[string "=[C]"]: ?

**Comment by madcowfred** [comment]
This is hopefully fixed with v11.0.0.3
